service: dio-live-serverless-project
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  iam:
      role:
          statements:
            - Effect: Allow
              Action:
                - dynamodb:PutItem
                - dynamodb:UpdateItem
                - dynamodb:GetItem
                - dynamodb:scan
              Resource:
                - arn:aws:dynamodb:us-east-1:851412669106:table/ItemTableNew

functions:
  api:
    handler: src/handler.hello
    events:
      - httpApi:
          path: /
          method: get
  insertItem:
    handler: src/insertItem.handler
    events:
      - http:
          path: /item
          method: post
  fetchItens:
    handler: src/fetchItens.handler
    events:
      - http:
          path: /itens
          method: get
  fetchItem2:
    handler: src/fetchItem.handler
    events:
      - http:
          path: /itens/{id}
          method: get
  updateItem:
    handler: src/updateItem.handler
    events:
      - http:
          path: /itens/{id}
          method: put
resources:
  Resources:
    ItemTableNew:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ItemTableNew
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH